config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  mount Resque::Server, at: '/jobs'

  post 'support/request_support'

  resources :feedbacks
  namespace :api do
    namespace :v1 do
      resources :masters
      resources :tattoos do
        collection do
          get 'by_part/:part', to: 'tattoos#by_part', as: 'parted'
          get 'by_style/:style', to: 'tattoos#by_style', as: 'styled'
          get 'tags', to: 'tattoos#tags'
        end
      end

      resources :masters do
        resources :tattoos
      end

      # resources :subscriptions

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end
    end
  end

  namespace :admin do
    resources :masters do
      resources :tattoos
      resources :feedbacks, only: [ :index, :delete]
    end

    resources :masters
    resources :tattoos do
      collection do
        get 'by_part/:part', to: 'tattoos#by_part', as: "parted"
        get 'by_style/:style', to: 'tattoos#by_style', as: "styled"
      end
    end

    resources :tags, only: [:index]
    resources :subscriptions
    resources :feedbacks
  end

  resources :users do
    get 'favorite_tattoos', to: 'users#favorite_tattoos', on: :member
  end

  resources :masters do
    resources :tattoos
    resources :feedbacks
  end

  resources :tattoos do
    collection do
      get 'by_part/:part', to: 'tattoos#by_part', as: "parted"
      get 'by_style/:style', to: 'tattoos#by_style', as: "styled"
    end

    # member do
    #   get 'toggle_favourite', to: 'tattoos#toggle_favourite', as: 'toggle_favourite'
    # end

    post 'toggle_favorite', on: :member
  end

  resources :tattoos
  resources :feedbacks, except: [:index, :show]
  resources :subscriptions, only: [ :show, :create]

  devise_for :users

  get '/promo', to: 'welcome#index'
  get '/team', to: 'welcome#team'
  get 'welcome/search'
  # get 'welcome/assistance'

  root "tattoos#index"
end

app/models/master.rb
class Master < ApplicationRecord
  belongs_to :user
  has_many :tattoos, dependent: :destroy
  has_many :feedbacks, dependent: :destroy
  
  mount_uploader :master_image, MasterImageUploader
  
  validates :name, :nickname, :user_id, :master_image, presence: true
end

app/controllers/admin/masters_controller.rb
class Admin::MastersController < Admin::ApplicationController
  before_action :set_master, only: %i[show edit update destroy]


  # GET /masters or /masters.json
  def index
    if current_user&.is_master?
      # User has master privileges, display all masters
      @user_masters = Master.where(user: current_user)
      @other_masters = Master.where.not(user: current_user)
    else
      # User does not have master privileges, display only their master if it exists
      @user_masters = [current_user&.master].compact
      @other_masters = Master.where.not(user: current_user)
    end
    @masters = @user_masters + @other_masters
  end

  # GET /masters/1 or /masters/1.json
  def show
    @tattoos = @master.tattoos
  end

  # GET /masters/new
  def new
    @users = User.all
    # Add this line to check the value of @users
    p @users
    @master = Master.new
  end

  # GET /masters/1/edit
  def edit
    @users = User.all
  end

  # POST /masters or /masters.json
  def create
    @master = Master.new(master_params)
    # @master.user = current_user # Set the user for this master

    respond_to do |format|
      if @master.save
        format.html { redirect_to admin_master_url(@master), notice: "Master was successfully created." }
        format.json { render :show, status: :created, location: @master }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masters/1 or /masters/1.json
  def update
    respond_to do |format|
      if @master.update(master_params)
        format.html { redirect_to admin_master_url(@master), notice: "Master was successfully updated." }
        format.json { render :show, status: :ok, location: @master }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masters/1 or /masters/1.json
  def destroy
    @master.destroy

    respond_to do |format|
      format.html { redirect_to admin_masters_url, notice: "Master was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master
      @master = Master.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def master_params
      params.require(:master).permit(:name, :nickname, :user_id)
    end

    def authorize_admin
      redirect_to root_path unless current_user&.is_admin?
    end
end

app/controllers/api/v1/masters_controller.rb
class Api::V1::MastersController < Api::V1::ApplicationController

  def index
    @masters = Master.all

    # render json: @masters
  end

  def show
    @master = Master.find(params[:id])
  end

  def create
    @user = User.find_by_jti(decrypt_payload[0]['jti'])
    @master = @user.master.new(master_params)

    if @master.save
      render json: @master.as_json
    else
      render json: @master.errors, status: :unprocessable_entity
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def master_params
      params.require(:master).permit(:name, :nickname)
    end
end

app/controllers/masters_controller.rb
class MastersController < ApplicationController
  load_and_authorize_resource
  before_action :authenticate_user!, except: [:index, :show]  # Allow unauthenticated access to index and show

  # GET /masters or /masters.json
  def index
    if current_user&.is_master?
      # User has master privileges, display all masters
      @user_masters = Master.where(user: current_user)
      @other_masters = Master.where.not(user: current_user)
    else
      # User does not have master privileges, display only their master if it exists
      @user_masters = [current_user&.master].compact
      @other_masters = Master.where.not(user: current_user)
    end
    @masters = @user_masters + @other_masters
  end

  # GET /masters/1 or /masters/1.json
  def show
    @master_tattoos = @master.tattoos
    # @master_image = @master.master_image.url
  end

  # GET /masters/new
  def new
    @master = Master.new
  end

  # GET /masters/1/edit
  def edit
  end

  # POST /masters or /masters.json
  def create
    @master = Master.new(master_params)
    # @master.user = current_user # Set the user for this master

    respond_to do |format|
      if @master.save

        WaitAndMakeJob.perform_later(@master, current_user)

        format.html { redirect_to master_url(@master), notice: "Master was successfully created." }
        format.json { render :show, status: :created, location: @master }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /masters/1 or /masters/1.json
  def update
    respond_to do |format|
      if @master.update(master_params.except(:user_id))
        format.html { redirect_to master_url(@master), notice: "Master was successfully updated." }
        format.json { render :show, status: :ok, location: @master }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @master.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /masters/1 or /masters/1.json
  def destroy
    @master.destroy

    respond_to do |format|
      format.html { redirect_to masters_url, notice: "Master was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_master
      @master = Master.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def master_params
      params.require(:master).permit(:name, :nickname, :master_image).merge(user_id: current_user.id)
    end
end

app/helpers/masters_helper.rb
module MastersHelper
  def owns_master?(master)
    user_signed_in? && (can?(:manage, master) || master.user == current_user)
  end
end

app/views/admin/masters/_form.html.erb
<%= form_with(model: [:admin, @master]) do |form| %>
  <% if master.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(master.errors.count, "error") %> prohibited this master from being saved:</h2>
      <ul>
        <% master.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :nickname, style: "display: block" %>
    <%= form.text_field :nickname %>
  </div>
  <div class="field">
    <%= form.label :user_id, "Select User" %>
    <%= form.collection_select :user_id, @users, :id, :email, include_blank: true %>
  </div>
  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/masters/_master.html.erb
<% index ||= 0 %>
<tr id="<%= dom_id master %>">
  <th scope="row"><%= index + 1 %></th>
  <td><%= master.user.email %></td>
  <td><%= master.name %></td>
  <td><%= master.nickname %></td>
  <td>
    <%= link_to "View", admin_master_path(master) %>
    <%= link_to "Edit", edit_admin_master_path(master) %>
    <%= button_to "Destroy", admin_master_path(master), method: :delete %>
  </td>
</tr>

app/views/admin/masters/edit.html.erb
<h1>Editing master</h1>
<%= render "form", master: @master %>
<br>
<div>
  <%= link_to "Show this master", @master %> |
  <%= link_to "Back to masters", masters_path %>
</div>

app/views/admin/masters/index.html.erb
<h1>Masters</h1>
<% if notice.present? %>
  <%= content_tag(:p, notice, class: 'inline-block px-3 py-2 mb-5 font-medium bg-black text-white', id: 'notice') %>
<% end %>

<% if can?(:create, Master) %>
  <%= link_to "New master", new_admin_master_path %>
<% end %>

<table role="grid">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">E-mail</th>
      <th scope="col">Name</th>
      <th scope="col">NickName</th>
      <th scope="col">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @masters.each_with_index do |master, index| %>
      <%= render partial: 'admin/masters/master', locals: { master: master, index: index } %>
    <% end %>
  </tbody>
</table>

app/views/admin/masters/new.html.erb
<h1>New master</h1>
<%= render "form", master: @master %>
<br>
<div>
  <%= link_to "Back to masters", admin_masters_path %>
</div>

app/views/admin/masters/show.html.erb
<% if notice.present? %>
  <%= content_tag(:p, notice, class: 'inline-block px-3 py-2 mb-5 font-medium bg-black text-white', id: 'notice') %>
<% end %>

<table role="grid">
  <tbody>
    <%= render partial: 'admin/masters/master', locals: { master: @master } %>
  </tbody>
</table>

<hr>

<h2>Tattoos:</h2>
<%= link_to "New tattoo", new_admin_master_tattoo_path(@master) %>

<div id="tattoos-card">
  <% @tattoos.each do |tattoo| %>
    <div class="tattoo-card">
      <%= link_to admin_tattoo_path(tattoo) do %>
        <table role="grid">
          <tbody>
            <%= render partial: "admin/tattoos/tattoo", locals: { master: @master, tattoo: tattoo } %>
          </tbody>
        </table>
      <% end %>
    </div>
  <% end %>
</div>

<hr>

<h2>Feedbacks:</h2>

<div id="feedbacks">
  <% @master.feedbacks.each do |feedback| %>
    <div class="feedback-card">
      <%= render partial: "feedbacks/feedback", locals: { master: @master, feedback: feedback } %>
    </div>
  <% end %>
</div>