config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  mount Resque::Server, at: '/jobs'

  post 'support/request_support'

  resources :feedbacks
  namespace :api do
    namespace :v1 do
      resources :masters
      resources :tattoos do
        collection do
          get 'by_part/:part', to: 'tattoos#by_part', as: 'parted'
          get 'by_style/:style', to: 'tattoos#by_style', as: 'styled'
          get 'tags', to: 'tattoos#tags'
        end
      end

      resources :masters do
        resources :tattoos
      end

      # resources :subscriptions

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end
    end
  end

  namespace :admin do
    resources :masters do
      resources :tattoos
      resources :feedbacks, only: [ :index, :delete]
    end

    resources :masters
    resources :tattoos do
      collection do
        get 'by_part/:part', to: 'tattoos#by_part', as: "parted"
        get 'by_style/:style', to: 'tattoos#by_style', as: "styled"
      end
    end

    resources :tags, only: [:index]
    resources :subscriptions
    resources :feedbacks
  end

  resources :users do
    get 'favorite_tattoos', to: 'users#favorite_tattoos', on: :member
  end

  resources :masters do
    resources :tattoos
    resources :feedbacks
  end

  resources :tattoos do
    collection do
      get 'by_part/:part', to: 'tattoos#by_part', as: "parted"
      get 'by_style/:style', to: 'tattoos#by_style', as: "styled"
    end

    # member do
    #   get 'toggle_favourite', to: 'tattoos#toggle_favourite', as: 'toggle_favourite'
    # end

    post 'toggle_favorite', on: :member
  end

  resources :tattoos
  resources :feedbacks, except: [:index, :show]
  resources :subscriptions, only: [ :show, :create]

  devise_for :users

  get '/promo', to: 'welcome#index'
  get '/team', to: 'welcome#team'
  get 'welcome/search'
  # get 'welcome/assistance'

  root "tattoos#index"
end

app/models/tattoo.rb
class Tattoo < ApplicationRecord
  include PgSearch::Model
  multisearchable against: [:title]

  extend FriendlyId
  friendly_id :title, use: :slugged

  belongs_to :master
  belongs_to :user, optional: true

  has_many :favourites
  has_many :users_who_favourited, through: :favourites, source: 'user'

  has_many :favorites, dependent: :destroy
  has_many :favorited_by, through: :favorites, source: :user

  mount_uploader :tattoo_image, TattooImageUploader

  acts_as_taggable_on :parts
  acts_as_taggable_on :styles

  validates :title, presence: true
  validates :tattoo_image, presence: true

  # self.per_page = 28
end

app/controllers/admin/tattoos_controller.rb
class Admin::TattoosController < Admin::ApplicationController
  before_action :set_tattoo, only: %i[ show edit update destroy ]

  # GET /tattoos or /tattoos.json
  def index
    @tattoos = Tattoo.all
  end

  def by_part
    @tattoos = Tattoo.tagged_with(params[:part])
    @display_master = true
    render :index
  end

  def by_style
    @tattoos = Tattoo.tagged_with(params[:style])
    @display_master = true
    render :index
  end

  # GET /tattoos/1 or /tattoos/1.json
  def show
    @master = @tattoo.master
  end

  # GET /tattoos/new
  def new
    @master = Master.find(params[:master_id])
    @tattoo = Tattoo.new
  end

  # GET /tattoos/1/edit
  def edit
    @master = @tattoo.master
  end

  # POST /tattoos or /tattoos.json
  def create
    @master = Master.find(params[:master_id])
    @tattoo = Tattoo.new(title: params[:tattoo][:title], part_list: params[:tattoo][:part_list], style_list: params[:tattoo][:style_list], master_id: @master.id)
    @tattoo.master = @master
    @tattoo.user = nil  # Set the user to nil for admin-created tattoos

    if params[:tattoo][:tattoo_image].present?
      @tattoo.tattoo_image = params[:tattoo][:tattoo_image]
    else
      @tattoo.tattoo_image = ''
    end

    respond_to do |format|
      if @tattoo.save
        format.html { redirect_to admin_tattoo_url(@tattoo), notice: "Tattoo was successfully created." }
        format.json { render :show, status: :created, location: @tattoo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tattoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tattoos/1 or /tattoos/1.json
  def update
    @master = @tattoo.master

    respond_to do |format|
      if @tattoo.update(tattoo_params)
        format.html { redirect_to admin_tattoo_url(@tattoo), notice: "Tattoo was successfully updated." }
        format.json { render :show, status: :ok, location: admin_tattoos_url }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tattoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tattoos/1 or /tattoos/1.json
  def destroy
    @master = @tattoo.master
    @tattoo.destroy

    respond_to do |format|
      format.html { redirect_to admin_tattoos_url, notice: "Tattoo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tattoo
      @tattoo = Tattoo.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tattoo_params
      params.require(:tattoo).permit(:title, :tattoo_image, :part_list, :style_list)
    end
end

app/controllers/api/v1/tattoos_controller.rb
class Api::V1::TattoosController < Api::V1::ApplicationController
  before_action :set_tattoos, only: [:by_part, :by_style]

  def index
    @tattoos = Tattoo.all
    # @new_tattoo_url = new_api_v1_master_tattoo_url(master_id: 1)
  end

  def show
  end

  def tags
    @parts_tags = Tattoo.tag_counts_on(:parts).pluck(:name)
    @styles_tags = Tattoo.tag_counts_on(:styles).pluck(:name)

    render json: { parts: @parts_tags, styles: @styles_tags }
  end

  def create
    @user = User.find_by_jti(decrypt_payload[0]['jti'])

    if @user.present?
      @master = @user.master

      @tattoo = @master.tattoos.new(tattoo_params)
      @tattoo.user_id = @user.id

      if params[:tattoo][:tattoo_image].present?
        @tattoo.tattoo_image = params[:tattoo][:tattoo_image]
      end

      if @tattoo.save
        render json: @tattoo.as_json, status: :created
      else
        render json: @tattoo.errors, status: :unprocessable_entity
      end
    else
      render json: { error: 'User not found' }, status: :not_found
    end
  end

  # def by_part
  #   @tags = Tattoo.tag_counts_on(:parts).pluck(:name)
  #   render json: { tags: @tags }
  # end

  # def by_style
  #   @tags = Tattoo.tag_counts_on(:styles).pluck(:name)
  #   render json: { tags: @tags }
  # end

  private

  def set_tattoos
    if params[:part]
      @tattoos = Tattoo.tagged_with(params[:part])
    elsif params[:style]
      @tattoos = Tattoo.tagged_with(params[:style])
    else
      @tattoos = Tattoo.all
    end
  end

  # Only allow a list of trusted parameters through.
  # def tattoo_params
  #   params.require(:tattoo).permit(:title, :tattoo_image, :part_list, :style_list)
  # end

  def tattoo_params
    params.require(:tattoo).permit(:title, :master_id, :tattoo_image)
  end

  # def tattoo_params
  #   params.require(:tattoo).permit(:title, :part_list, :style_list, :master_id)
  # end

end

app/controllers/tattoos_controller.rb
class TattoosController < ApplicationController
  include TattoosHelper
  load_and_authorize_resource
  before_action :set_tattoo, only: %i[ show edit update destroy toggle_favourite ]
  before_action :authenticate_user!, only: [:toggle_favorite]

  # GET /tattoos or /tattoos.json
  def index
    # @tattoos = Tattoo.paginate(page: params[:page])
    @tattoos = Tattoo.all
    @display_master = true

    if user_signed_in?  # Check if the user is signed in using your authentication logic
      @tattooos = current_user.tattoos
    else
      # Handle the case where the user is not authenticated
      # For example, you can display public content or a message
    end
  end

  def by_part
    @tattoos = Tattoo.tagged_with(params[:part])
    @display_master = true
    render :index
  end

  def by_style
    @tattoos = Tattoo.tagged_with(params[:style])
    @display_master = true
    render :index
  end

  def toggle_favorite
    @tattoo = Tattoo.find(params[:id])
    if current_user.favorite_tattoos.exists?(@tattoo.id)
      current_user.favorite_tattoos.delete(@tattoo)
      render json: { status: 'removed' }
    else
      current_user.favorite_tattoos << @tattoo
      render json: { status: 'added' }
    end
  end

  # GET /tattoos/1 or /tattoos/1.json
  def show
    @display_master = true
    @master = @tattoo.master

    @tattoos = Tattoo.tagged_with(@tattoo.part_list, any: true)
                    .tagged_with(@tattoo.style_list, any: true)
                    .where.not(id: @tattoo.id)
  end

  # GET /tattoos/new
  def new
    @master = Master.find(params[:master_id])
    @tattoo = Tattoo.new
  end

  # GET /tattoos/1/edit
  def edit
    @master = @tattoo.master
  end

 def search
      @items = PgSearch.multisearch(params['search'])
  end

  # POST /tattoos or /tattoos.json
  def create
    @master = Master.find(params[:master_id])
    @tattoo = Tattoo.new(title: params[:tattoo][:title], part_list: params[:tattoo][:part_list], style_list: params[:tattoo][:style_list], master_id: @master.id)
    @tattoo.user = current_user


    if params[:tattoo][:tattoo_image].present?
      @tattoo.tattoo_image = params[:tattoo][:tattoo_image]
    else
      @tattoo.tattoo_image = ''
    end

    respond_to do |format|
      if @tattoo.save
        format.html { redirect_to tattoo_url(@tattoo), notice: "Tattoo was successfully created." }
        format.json { render :show, status: :created, location: @tattoo }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @tattoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tattoos/1 or /tattoos/1.json
  def update
    @master = @tattoo.master

    respond_to do |format|
      if @tattoo.update(tattoo_params)
        format.html { redirect_to tattoo_url(@tattoo), notice: "Tattoo was successfully updated." }
        format.json { render :show, status: :ok, location: @tattoo }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @tattoo.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tattoos/1 or /tattoos/1.json
  def destroy
    @master = @tattoo.master
    @tattoo.destroy

    respond_to do |format|
      format.html { redirect_to master_url(@master), notice: "Tattoo was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tattoo
      @tattoo = Tattoo.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def tattoo_params
      params.require(:tattoo).permit(:title, :tattoo_image, :part_list, :style_list)
    end
end

app/helpers/tattoos_helper.rb
module TattoosHelper
  def can_modify_tattoo?(tattoo)
    user_signed_in? && (can?(:manage, tattoo.master) || tattoo.user == current_user)
  end
end

app/views/tattoos/_favourite_button.html.erb
<%
  tattoo_user_ids = []

  tattoo.users_who_favourited.each do |user|
    tattoo_user_ids << user.id
  end

  # if current_user
  #   favourite_icon = tattoo_user_ids.include?(current_user.id) ? '+' : '-'
  # else
  #   favourite_icon = ''
  # end
%>

<%= turbo_frame_tag dom_id(tattoo) do %>
  <div class="absolute px-4 pt-0 pb-1 text-4xl text-white duration-150 bg-black opacity-0 bottom-5 right-7 group-hover:opacity-100">
    <%= link_to "+", toggle_favourite_tattoo_path(tattoo), class: 'hover:no-underline leading-[1.5]' %>
  </div>
<% end %>

app/views/tattoos/_form.html.erb
<section class="grid w-full place-items-center">
  <%= form_with(model: [master, tattoo], class: 'w-full space-y-2') do |form| %>
    <% if tattoo.errors.any? %>
      <div style="color: red">
        <h2><%= pluralize(tattoo.errors.count, "error") %> prohibited this tattoo from being saved:</h2>
        <ul>
          <% tattoo.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="w-full">
      <h1>название</h1>
      <%= form.text_field :title, class: "w-full" %>
    </div>

    <div class="w-full">
      <h1>часть тела</h1>
      <%= form.text_field :part_list, value: tattoo.part_list.join(", "), class: "w-full" %>
    </div>

    <div class="w-full">
      <h1>цвет</h1>
      <%= form.text_field :style_list, value: tattoo.style_list.join(", "), class: "w-full" %>
    </div>

    <div class="w-full">
      <%= form.file_field :tattoo_image, class: "form-control", class: "w-full space-x-2" %>
    </div >

    <div class="w-full">
      <%= form.submit 'Создать', class: 'block w-full !mt-3 px-5 py-2.5 text-lg text-center font-book border-2 duration-200 rounded-10 bg-black text-white border-transparent hover:opacity-[85%]' %>
    </div>
  <% end %>
</section>

app/views/tattoos/_search_results.html.erb
<div class="grid grid-cols-4 mt-10 xl:grid-cols-3 sm:grid-cols-1 gap-7" id="search_preview">
  <% items.each do |item| %>
    <%= render item.searchable %>
  <% end %>
</div>

app/views/tattoos/_tattoo.html.erb
<article id="<%= dom_id tattoo %>" class="h-auto">
  <%= link_to tattoo do %>
    <%= image_tag tattoo.tattoo_image.url, class: "object-cover s-full #{@preview_mode == :enabled ? 'group-hover:scale-105 duration-300' : ''}" %>
  <% end %>

  <%= link_to tattoos_path do %>
    <%= image_tag "icons/add.svg", class: "object-cover s-12 sm:s-10 absolute hidden p-3.5 sm:p-3 duration-300 bg-black bottom-3 right-3 group-hover:block hover:bg-opacity-70 sm:active:bg-opacity-80 sm:hover:bg-opacity-100" %>
  <% end %>
</article>

app/views/tattoos/_tattoos_next_button.html.erb
<%= turbo_frame_tag 'tattoos_pagination' do %>
  <% if tattoos.next_page %>
    <%= link_to 'еще татушки', tattoos_url(page: tattoos.next_page), data: {turbo_stream: true, tattoos_target: 'nextButton'} %>
  <% end %>
<% end %>

app/views/tattoos/_tattoos_segment.html.erb
<div class="grid grid-cols-4 gap-7">
  <% tattoos.each do |tattoo| %>
    <% master = tattoo.master %>
    <%= render partial: 'tattoos/tattoo', locals: { master: master, tattoo: tattoo } %>
  <% end %>
</div>

app/views/tattoos/edit.html.erb
<h1>Editing tattoo</h1>
<%= render "form", master: @master, tattoo: @tattoo %>
<br>
<div>
  <%= link_to "Show this tattoo", @tattoo %>
</div>

app/views/tattoos/index.html.erb
<section data-section="tattoo-index">
  <%= render Views::Tattoos::TattoosConfigComponent.new() %>
  <%= render Views::Tattoos::TattoosGridComponent.new(tattoos: @tattoos, className: '') %>
</section>

app/views/tattoos/new.html.erb
<section data-section="tattoo-show" class="mt-12 sm:mt-10 space-y-3 <%= Constants::TATTOO_PAGE_WIDTH %>" class="">
  <%= render(Ui::HeadingComponent.new(className: 'sm:!text-2xl', text: 'Новая татуировка')) %>
  <%= render "form", master: @master, tattoo: @tattoo %>
</section>

app/views/tattoos/search.html.erb
<%= render 'search_results', items: @items %>

app/views/tattoos/search.turbo_stream.erb
<%= turbo_stream.replace 'search_preview', partial: "search_results", locals: { items: @items} %>

app/views/tattoos/show.html.erb
<% if notice.present? %>
  <%= content_tag(:p, notice, class: 'inline-block px-3 py-2 mb-5 font-medium bg-black text-white', id: 'notice') %>
<% end %>

<%= render Views::Tattoos::TattooComponent.new(tattoo: @tattoo, master: @master ) %>

<section data-section="tattoo-show" class="mt-12 sm:mt-10 space-y-3 <%= Constants::TATTOO_PAGE_WIDTH %>" class="">
  <%= render(Ui::CaptionComponent.new(className: 'sm:!text-2xl', text: 'Похожие татуировки')) %>
  <%= render Views::Tattoos::TattoosGridComponent.new(tattoos: @tattoos, className: '') %>
</section>

app/views/tattoos/toggle_favourite.html.erb
<%= render 'tattoos/favourite_button', tattoo: @tattoo %>