config/routes.rb
Rails.application.routes.draw do
  require 'resque/server'
  mount Resque::Server, at: '/jobs'

  post 'support/request_support'

  resources :feedbacks
  namespace :api do
    namespace :v1 do
      resources :masters
      resources :tattoos do
        collection do
          get 'by_part/:part', to: 'tattoos#by_part', as: 'parted'
          get 'by_style/:style', to: 'tattoos#by_style', as: 'styled'
          get 'tags', to: 'tattoos#tags'
        end
      end

      resources :masters do
        resources :tattoos
      end

      # resources :subscriptions

      devise_scope :user do
        post "sign_up", to: "registrations#create"
        post "sign_in", to: "sessions#create"
        post "sign_out", to: "sessions#destroy"
      end
    end
  end

  namespace :admin do
    resources :masters do
      resources :tattoos
      resources :feedbacks, only: [ :index, :delete]
    end

    resources :masters
    resources :tattoos do
      collection do
        get 'by_part/:part', to: 'tattoos#by_part', as: "parted"
        get 'by_style/:style', to: 'tattoos#by_style', as: "styled"
      end
    end

    resources :tags, only: [:index]
    resources :subscriptions
    resources :feedbacks
  end

  resources :users do
    get 'favorite_tattoos', to: 'users#favorite_tattoos', on: :member
  end

  resources :masters do
    resources :tattoos
    resources :feedbacks
  end

  resources :tattoos do
    collection do
      get 'by_part/:part', to: 'tattoos#by_part', as: "parted"
      get 'by_style/:style', to: 'tattoos#by_style', as: "styled"
    end

    # member do
    #   get 'toggle_favourite', to: 'tattoos#toggle_favourite', as: 'toggle_favourite'
    # end

    post 'toggle_favorite', on: :member
  end

  resources :tattoos
  resources :feedbacks, except: [:index, :show]
  resources :subscriptions, only: [ :show, :create]

  devise_for :users

  get '/promo', to: 'welcome#index'
  get '/team', to: 'welcome#team'
  get 'welcome/search'
  # get 'welcome/assistance'

  root "tattoos#index"
end

app/models/subscription.rb
class Subscription < ApplicationRecord
    validates :email, presence: true
end

app/controllers/admin/subscriptions_controller.rb
class Admin::SubscriptionsController < Admin::ApplicationController
  before_action :set_subscription, only: %i[ show edit update destroy ]

  # GET /subscriptions or /subscriptions.json
  def index
    @subscriptions = Subscription.all
  end

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # GET /subscriptions/new
  def new
    @subscription = Subscription.new
  end

  # GET /subscriptions/1/edit
  def edit
    @subscription = Subscription.find(params[:id])
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to admin_subscriptions_url, notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /subscriptions/1 or /subscriptions/1.json
  def update
    respond_to do |format|
      if @subscription.update(subscription_params)
        format.html { redirect_to admin_subscriptions_url, notice: "Subscription was successfully updated." }
        format.json { render :show, status: :ok, location: @subscription }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /subscriptions/1 or /subscriptions/1.json
  def destroy
    @subscription.destroy

    respond_to do |format|
      format.html { redirect_to admin_subscriptions_url, notice: "Subscription was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_subscription
      @subscription = Subscription.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:email)
    end
end

app/controllers/subscriptions_controller.rb
class SubscriptionsController < ApplicationController

  # GET /subscriptions/1 or /subscriptions/1.json
  def show
  end

  # POST /subscriptions or /subscriptions.json
  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html { redirect_to subscription_url(@subscription), notice: "Subscription was successfully created." }
        format.json { render :show, status: :created, location: @subscription }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @subscription.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Only allow a list of trusted parameters through.
    def subscription_params
      params.require(:subscription).permit(:email)
    end
end

app/helpers/subscriptions_helper.rb
module SubscriptionsHelper
end

app/views/admin/subscriptions/_form.html.erb
<%= form_with(model: @subscription, url: admin_subscriptions_path) do |form| %>
  <% if subscription.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(subscription.errors.count, "error") %> prohibited this subscription from being saved:</h2>
      <ul>
        <% subscription.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div>
    <%= form.label :email, style: "display: block" %>
    <%= form.email_field :email %>
  </div>
  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/admin/subscriptions/_subscription.html.erb
<% index ||= 0 %>
<tr id="<%= dom_id subscription %>">
  <th scope="row"><%= index + 1 %></th>
  <td><%= subscription.email %></td>
  <td><%= subscription.created_at.strftime("%B %d, %Y %I:%M %p") %></td>
  <td><%= button_to "Destroy this subscription", admin_subscription_path(subscription), method: :delete %></td>
</tr>

app/views/admin/subscriptions/edit.html.erb
<h1>Editing subscription</h1>
<%= render "form", subscription: @subscription %>
<br>
<div>
  <%= link_to "Show this subscription", admin_subscription_path(@subscription) %> |
  <%= link_to "Back to subscriptions", subscriptions_path %>
</div>

app/views/admin/subscriptions/index.html.erb
<h1>Subscriptions</h1>
<% if notice.present? %>
  <%= content_tag(:p, notice, class: 'inline-block px-3 py-2 mb-5 font-medium bg-black text-white', id: 'notice') %>
<% end %>
<%= link_to "New subscription", new_admin_subscription_path %>
<table role="grid">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">E-mail</th>
      <th scope="col">Date</th>
      <th scope="col">Action</th>
    </tr>
  </thead>
  <tbody>
    <% @subscriptions.each_with_index do |master, index| %>
      <%= render partial: 'subscription', locals: { subscription: master, index: index } %>
    <% end %>
  </tbody>
</table>

app/views/admin/subscriptions/new.html.erb
<h1>New subscription</h1>
<%= render "form", subscription: @subscription %>
<br>
<div>
  <%= link_to "Back to subscriptions", admin_subscriptions_path %>
</div>

app/views/admin/subscriptions/show.html.erb
<% if notice.present? %>
  <%= content_tag(:p, notice, class: 'inline-block px-3 py-2 mb-5 font-medium bg-black text-white', id: 'notice') %>
<% end %>

<%= render @subscription %>
<div>
  <%= link_to "Edit this subscription", edit_subscription_path(@subscription) %> |
  <%= link_to "Back to subscriptions", admin_subscriptions_path %>
  <%= button_to "Destroy this subscription", @subscription, method: :delete %>
</div>